-------------------------------------------------------------------------------
Test set: cn.org.sqx.mall.product.webapi.mapper.CategoryMapperTests
-------------------------------------------------------------------------------
Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.189 s <<< FAILURE! - in cn.org.sqx.mall.product.webapi.mapper.CategoryMapperTests
testGetByNameSuccessfully  Time elapsed: 0.036 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Unexpected exception thrown: org.opentest4j.AssertionFailedError: expected: not <null>
	at cn.org.sqx.mall.product.webapi.mapper.CategoryMapperTests.testGetByNameSuccessfully(CategoryMapperTests.java:43)
Caused by: org.opentest4j.AssertionFailedError: expected: not <null>
	at cn.org.sqx.mall.product.webapi.mapper.CategoryMapperTests.lambda$testGetByNameSuccessfully$1(CategoryMapperTests.java:47)
	at cn.org.sqx.mall.product.webapi.mapper.CategoryMapperTests.testGetByNameSuccessfully(CategoryMapperTests.java:43)

